# Generated by Django 5.2.4 on 2025-07-22 15:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("image", models.ImageField(upload_to="products/")),
                ("date_added", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("electronics", "Electronics"),
                            ("clothing", "Clothing"),
                            ("home_appliances", "Home Appliances"),
                            ("books", "Books"),
                            ("toys", "Toys"),
                            ("sports", "Sports"),
                            ("beauty", "Beauty"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
        ),
    ]
