# Generated by Django 5.2.4 on 2025-07-23 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecom", "0002_product_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="product",
            name="stock",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
