# Generated by Django 5.2.4 on 2025-07-23 12:27

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ecom", "0004_product_review_store"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Product_review",
            new_name="ProductReview",
        ),
    ]
