# Generated by Django 5.2.4 on 2025-07-23 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecom", "0005_rename_product_review_productreview"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductCertificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certificate",
                        to="ecom.product",
                    ),
                ),
            ],
        ),
    ]
