# Generated by Django 5.2.4 on 2025-07-24 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecom", "0006_productcertificate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="store",
            name="store",
            field=models.ManyToManyField(related_name="stores", to="ecom.product"),
        ),
    ]
